const productsData = [
    {
        id: 1,
        nombre: "MATE IMPERIAL PREMIUM",
        precio: 30, 
        category: "mate",
        productImg: "./assets/products/mates/ImperialLiso.jpeg",
    },
    {
        id: 2,
        nombre: "MOCHILA MATEANDO", 
        precio: 15, 
        category: "accesorios",
        productImg: "./assets/products/accesorios/mochila.jpeg",
    },
    {
        id: 3,
        nombre: "Bombilla Pico de Loro",
        precio: 10, 
        category: "bombilla",
        productImg: "./assets/products/bombillas/picoloro1.jpeg",
    },
    {
        id: 4,
        nombre: "Termo Media Manija",
        precio: 35, 
        category: "accesorios",
        productImg: "./assets/products/accesorios/termo.jpeg",
    },
    {
        id: 5,
        nombre: "Termo Personalizado",
        precio: 40, 
        category: "accesorios",
        productImg: "./assets/products/accesorios/termopersonalizado.jpeg",
    },
    {
        id: 6,
        nombre: "BOMBILLON de Alpaca",
        precio: 15, 
        category:"bombilla",
        productImg: "./assets/products/bombillas/bombillon.jpeg",
    },
    {
        id: 7,
        nombre: "MATE ACERO TÉRMICO",
        precio: 20, 
        category: "mate",
        productImg: "./assets/products/mates/mateacero.jpeg",
    },
    {
        id: 8,
        nombre: "TORPEDO CINCELADO",
        precio: 30, 
        category: "mate",
        productImg: "./assets/products/mates/torpedo.jpeg",
    },
    {
        id: 9,
        nombre: "MATE CAMIONERO PREMIUM",
        precio: 25, 
        category: "mate",
        productImg: "./assets/products/mates/camionero.jpeg",
    },
    {
        id: 10,
        nombre: "YERBERA DE CUERO",
        precio: 10, 
        category: "accesorios",
        productImg: "./assets/products/accesorios/yerbero.jpeg",
    },
    {
        id: 11,
        nombre: "MATERA DE CUERO GRUESO",
        precio: 15, 
        category: "accesorios",
        productImg: "./assets/products/accesorios/matera.jpeg",
    },
    {
        id: 12,
        nombre: "YERBERA TAMBO",
        precio: 10, 
        category: "accesorios",
        productImg: "./assets/products/accesorios/yerbero1.jpeg",
    },
    {
        id: 13,
        nombre: "MATE IMPERIAL ALGARROBO",
        precio: 35, 
        category: "mate",
        productImg: "./assets/products/mates/matealgarrobo.png",
    },
    {
        id: 14,
        nombre: "MATE DE ALGARROBO",
        precio: 30, 
        category: "mate",
        productImg: "./assets/products/mates/matealgarrobo1.jpeg",
    },
    {
        id: 15,
        nombre: "Bombilla Alpaca Cincelada",
        precio: 15, 
        category: "bombilla",
        productImg: "./assets/products/bombillas/cincelada.jpeg",
    },
    {
        id: 16,
        nombre: "BOMBILLÓN Pico de Rey",
        precio: 10, 
        category: "bombilla",
        productImg: "./assets/products/bombillas/picorey.jpeg",
    },
    {
        id: 17,
        nombre: "MATE DE CERÁMICA",
        precio: 25, 
        category: "mate",
        productImg: "./assets/products/mates/ceramica.jpeg",
    },
    {
        id: 18,
        nombre: "IMPERIAL DELUXE BLANCO",
        precio: 30, 
        category: "mate",
        productImg: "./assets/products/mates/blanco.jpeg",
    },
    {
        id: 19,
        nombre: "Yerba Despalada Matesur",
        precio: 12, 
        category: "yerba",
        productImg: "./assets/products/yerbas/yerba1.webp",
    },
    {
        id: 20,
        nombre: "Yerba CANARIAS Uruguaya",
        precio: 15, 
        category: "yerba",
        productImg: "./assets/products/yerbas/canarias.jpeg",
    },
]

